import type { DeckList } from "./commander.js";

/**
 * The Winota list - a real Commander deck, transcribed card for card.
 *
 * Not generated. The other archetypes in `archetypes.ts` are a commander, a pile
 * of cards the effect DSL happens to be able to express, and basics to fill; this
 * is somebody's actual 100, and every card in it was implemented because the deck
 * wanted it rather than the other way round. That is what
 * `docs/ADDING-CARDS.md` means by deck-led growth, and it is why this file is a
 * list of ids and nothing else: the work is all in `testCards.ts`.
 *
 * All 100 are implemented exactly - no approximations, no "close enough" - which
 * is checked three ways on demand by the audits in tools/scryfall-report and once
 * more by `winotaDeck.test.ts`, which asserts the list is legal Commander and
 * that every id in it resolves to a real fixture.
 *
 * Boros hatebears: tax and deny while Winota turns non-Human attackers into free
 * Humans off the top of the library.
 */
export const WINOTA_DECK: DeckList = {
  commanderId: "winota-joiner-of-forces",
  libraryIds: [
    "ainok-strike-leader",
    "ajani-nacatl-pariah",
    "alseid-of-lifes-bounty",
    "ancient-tomb",
    "angraths-marauders",
    "anim-pakal-thousandth-moon",
    "arcane-signet",
    "archivist-of-oghma",
    "archon-of-emeria",
    "arid-mesa",
    "aven-mindcensor",
    "battlefield-forge",
    "blade-historian",
    "blinkmoth-nexus",
    "boromir-warden-of-the-tower",
    "cathar-commando",
    "cavern-of-souls",
    "charismatic-conqueror",
    "chrome-mox",
    "city-of-brass",
    "city-of-traitors",
    "clarion-conqueror",
    "clifftop-retreat",
    "combat-celebrant",
    "command-tower",
    "deafening-silence",
    "deflecting-swat",
    "dollmakers-shop",
    "drannith-magistrate",
    "eiganjo-seat-of-the-empire",
    "emerias-call",
    "enlightened-tutor",
    "eomer-king-of-rohan",
    "esper-sentinel",
    "ethersworn-canonist",
    "gamble",
    "gemstone-caverns",
    "gingerbrute",
    "giver-of-runes",
    "goblin-cratermaker",
    "goblin-rabblemaster",
    "grand-abolisher",
    "greymond-avacyns-stalwart",
    "hexing-squelcher",
    "high-noon",
    "homeward-path",
    "imperial-recruiter",
    "inkmoth-nexus",
    "kiki-jiki-mirror-breaker",
    "legion-warboss",
    "lotus-petal",
    "loyal-apprentice",
    "mana-confluence",
    "mana-vault",
    "marsh-flats",
    "mother-of-runes",
    "mountain",
    "mox-amber",
    "mox-diamond",
    "multiversal-passage",
    "myrel-shield-of-argive",
    "needleverge-pathway",
    "ocelot-pride",
    "ornithopter",
    "ornithopter-of-paradise",
    "path-to-exile",
    "phyrexian-walker",
    "plains",
    "plateau",
    "professional-face-breaker",
    "pyroblast",
    "quicksilver-brash-blur",
    "ragavan-nimble-pilferer",
    "ranger-captain-of-eos",
    "raph-and-leo-sibling-rivals",
    "recruiter-of-the-guard",
    "red-elemental-blast",
    "rionya-fire-dancer",
    "rite-of-flame",
    "sacred-foundry",
    "sanctum-prelate",
    "scalding-tarn",
    "serra-ascendant",
    "shatterskull-smashing",
    "signal-pest",
    "silence",
    "simian-spirit-guide",
    "skrelv-defector-mite",
    "sokenzan-crucible-of-defiance",
    "sol-ring",
    "spirit-of-the-labyrinth",
    "starting-town",
    "sunbaked-canyon",
    "sunbillow-verge",
    "swords-to-plowshares",
    "voice-of-victory",
    "windcrag-siege",
    "windswept-heath",
    "zealous-conscripts",
  ],
};
